Update patch set 1
Patch Set 1:

> hi
 > i picked all of your patches to test with klte but i always get
 > this compilation error: http://prnt.sc/ceu6c2
 > did you also have some problems?

I don't have any compile warnings, but you might be better off using sources from AOSP directly since you are on the 3.10 kernel if I'm not mistaken.

Patch-set: 1